### ISSUE TITLE
Can't start server locally

### ISSUE THREAD

**Issue by fexxor** [europeana/OAI-PMH#32]
Hey, I'm trying to set everything up on my own computer, but I have problems with the dependencies. When trying to build with maven I get the following error:

`Non-resolvable parent POM for eu.europeana:oai-pmh2:0.0.2-SNAPSHOT: Could not find artifact eu.europeana:europeana-parent-pom:pom:2.0 in central (https://repo.maven.apache.org/maven2) and 'parent.relativePath' points at wrong local POM @ line 6, column 10 -> [Help 2]`

Is the parent pom missing, or am I skipping a step?

**Comment by P-Ehlert** [comment]
Hi. Thank you for your interest in our project. 

The OAI-PMH2 project uses 2 dependencies which we developed ourselves; europeana-parent-pom and Corelib. These projects are not available in the 'standard' Maven repositories, but they are in our own repository, so you have to add http://artifactory.eanadev.org/artifactory/libs-release and http://artifactory.eanadev.org/artifactory/libs-snapshot to either your maven settings.xml or to the project's pom.xml.

This should fix your build problems, but won't allow you to run a server yet. The OAI-PMH project was designed specifically for Europeana and connects to our MongoDb and Solr servers which are not open to the public, at least not directly. This means that you need to setup your own Mongo and Solr servers and specify those in the oai-pmh.properties file to have something that runs. Or you can adjust the code to connect to your own database of choice for course.
